# Generated by Django 2.0.7 on 2018-07-15 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plates', '0002_auto_20180715_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plate',
            name='license_number',
            field=models.CharField(max_length=6),
        ),
    ]
