# Generated by Django 2.0.7 on 2018-07-15 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plates', '0004_auto_20180715_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plate',
            name='license_number',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='plate',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plates', to='plates.Owner'),
        ),
    ]
