# Generated by Django 2.0.7 on 2018-07-15 18:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plates', '0005_auto_20180715_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphabetical letters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='owner',
            name='surname',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only alphabetical letters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='plate',
            name='license_number',
            field=models.CharField(max_length=6, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]{3}[0-9]{3}$', 'Wrong format. Please use ABC123 format.')]),
        ),
    ]
