language: ruby

services:
  - docker

before_install:
  - docker build -t fullbright/car-license-plate-api .
  - docker run -d -p 127.0.0.1:80:4567 fullbright/car-license-plate-api /bin/sh -c "cd /root/sinatra; bundle exec foreman start;"
  - docker ps -a
  - docker run fullbright/car-license-plate-api /bin/sh -c "cd /root/sinatra; bundle exec rake test"

script:
  - bundle exec rake test
